/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263.hw02;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String[] args) {

        PushbackTokenizer token1=new TokenAdapter("This is Object Oriented Programming");
        System.out.println(token1.nextToken());
        System.out.println(token1.nextToken());
        token1.pushback();
        System.out.println(token1.nextToken());
        System.out.println(token1.nextToken());
        token1.pushback();
        System.out.println(token1.nextToken());
        System.out.println(token1.nextToken());

    }
}
